services:
  app:
    build: .
    container_name: monopoly-app
    ports:
      - "8080:8080"
    environment:
      # Database (matches your appsettings.json structure)
      Database__Host: db
      Database__Port: ${DB_PORT}
      Database__Username: ${DB_USER}
      Database__Password: ${DB_PASS}
      Database__DatabaseName: ${DB_NAME}

      # Kafka
      Kafka__BootstrapServers: kafka:9092
      Kafka__ConsumerGroupId: ${KAFKA_GROUP}
      Kafka__GameEventsTopic: ${KAFKA_TOPIC_EVENTS}
      Kafka__GameControlTopic: ${KAFKA_TOPIC_CONTROL}
      Kafka__EnableAutoCommit: "false"

      # JWT & OAuth
      JWT__Issuer: ${JWT_ISSUER}
      JWT__Audience: ${JWT_AUDIENCE}
      JWT__Key: ${JWT_KEY}
      OAuth2__Discord__ClientId: ${DISCORD_CLIENT_ID}
      OAuth2__Discord__ClientSecret: ${DISCORD_CLIENT_SECRET}

      AllowedOrigins: ${ALLOWED_ORIGINS}

    depends_on:
      - db
      - kafka
      - kafka-setup

  db:
    image: postgres:16
    container_name: monopoly-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: monopoly-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: monopoly-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-setup:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-setup
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      kafka-topics --create --if-not-exists --topic ${KAFKA_TOPIC_EVENTS} --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 &&
      kafka-topics --create --if-not-exists --topic ${KAFKA_TOPIC_CONTROL} --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 &&
      sleep infinity
      "

volumes:
  db-data:
