name: Deploy to VPS

on:
  workflow_run:
    workflows: [Docker Publish]
    branches: [dev]
    types:
      - completed

jobs:
  on-success:
    environment: "development"
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        env:
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ vars.DB_NAME }}
          KAFKA_GROUP: ${{ vars.KAFKA_GROUP }}
          KAFKA_TOPIC_EVENTS: ${{ vars.KAFKA_TOPIC_EVENTS }}
          KAFKA_TOPIC_CONTROL: ${{ vars.KAFKA_TOPIC_CONTROL }}
          JWT_ISSUER: ${{ vars.JWT_ISSUER }}
          JWT_AUDIENCE: ${{ vars.JWT_AUDIENCE }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DB_PORT, DB_USER, DB_PASS, DB_NAME, KAFKA_GROUP, KAFKA_TOPIC_EVENTS, KAFKA_TOPIC_CONTROL, JWT_ISSUER, JWT_AUDIENCE, JWT_KEY, DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET, SENTRY_DSN, ALLOWED_ORIGINS
          script: |
            cd /opt/monopoly
            docker compose pull
            docker compose up -d
            docker image prune -af

