name: Deploy to VPS

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    environment: "development"
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/monopoly
            docker compose pull
            docker compose up -d
            docker image prune -af

