name: Deploy to VPS

on:
  push:
    branches:
      - main   # or dev if you want to auto-deploy dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{SSH_USER}}@${{SSH_HOST}} << 'EOF'
            cd /opt/monopoly
            docker compose pull
            docker compose up -d
          EOF
